//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_LIST
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime CREATED_TIMESTAMP { get; set; }
        public int CREATED_USER_ID { get; set; }
        public System.DateTime MODIFIED_TIMESTAMP { get; set; }
        public int MODIFIED_USER_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
