//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_LIST_ITEM
    {
        public int ID { get; set; }
        public int CHECK_LIST_ID { get; set; }
        public bool IS_COMPLETE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public bool ACTIVE { get; set; }
    
        public virtual CHECK_LIST CHECK_LIST { get; set; }
    }
}
