//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskDbEntities : DbContext
    {
        public TaskDbEntities()
            : base("name=TaskDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHECK_LIST> CHECK_LIST { get; set; }
        public virtual DbSet<CHECK_LIST_ITEM> CHECK_LIST_ITEM { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
